version: "3.7"

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # pgadmin:
  #   image: "dpage/pgadmin4"
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - 8080:80

volumes:
  db:
    driver: local
